<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import MarkdownView from '../components/MarkdownView.vue'
import {
  archivePlatformCase, getPlatformCase, listPlatformCases, listPlatforms,
  restorePlatformCase, updatePlatformCase, type PlatformCaseDetail, type PlatformCaseSummary,
  type PlatformProfile,
} from '../api/platformData'
import { useProjectStore } from '../projectStore'

interface TreeNode { id: string; label: string; children?: TreeNode[] }
const projects=useProjectStore()
const spaceId=projects.defaultWikiSpaceId
const platforms=ref<PlatformProfile[]>([]),rows=ref<PlatformCaseSummary[]>([])
const page=ref(1),pageSize=ref(20),total=ref(0)
const loading=ref(false),detailLoading=ref(false),drawer=ref(false),detail=ref<PlatformCaseDetail>(),dialog=ref(false),saving=ref(false)
const filters=reactive<{platform_id?:number;variant_id?:number;media_type:string;search:string;include_archived:boolean}>({media_type:'',search:'',include_archived:false})
const form=reactive({platform_id:undefined as number|undefined,variant_id:undefined as number|undefined,filename:'',name:'',kind:'combined',media_type:'application/json',content:''})
const filterPlatform=computed(()=>platforms.value.find(p=>p.id===filters.platform_id))
const formPlatform=computed(()=>platforms.value.find(p=>p.id===form.platform_id))

function treeValue(value:unknown,path='root',depth=0,state={nodes:0}):TreeNode[]{
  state.nodes+=1
  if(depth>20||state.nodes>2000)return [{id:`${path}.truncated`,label:'<truncated>'}]
  if(Array.isArray(value)){const output:TreeNode[]=[];for(let index=0;index<value.length;index+=1){if(state.nodes>=2000){output.push({id:`${path}.truncated`,label:'<truncated>'});break}output.push({id:`${path}.${index}`,label:`[${index}]`,children:treeValue(value[index],`${path}.${index}`,depth+1,state)})}return output}
  if(value!==null&&typeof value==='object'){const output:TreeNode[]=[];for(const [key,item] of Object.entries(value as Record<string,unknown>)){if(state.nodes>=2000){output.push({id:`${path}.truncated`,label:'<truncated>'});break}output.push({id:`${path}.${key}`,label:key,children:treeValue(item,`${path}.${key}`,depth+1,state)})}return output}
  return [{id:`${path}.value`,label:String(value)}]
}
const jsonTree=computed<TreeNode[]>(()=>detail.value?[{id:'root',label:'JSON',children:treeValue(detail.value.json_value)}]:[])
function safeName(filename:string){const base=filename.replace(/\\/g,'/').split('/').pop()||'platform-case.txt';const clean=base.replace(/[\u0000-\u001f\u007f]/g,'_').slice(0,240);return !clean||clean==='.'||clean==='..'?'platform-case.txt':clean}
function download(){if(!detail.value)return;const blob=new Blob([detail.value.content],{type:detail.value.media_type||'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=safeName(detail.value.filename);a.click();URL.revokeObjectURL(url)}
async function load(){if(!spaceId.value)return;loading.value=true;try{const result=await listPlatformCases(spaceId.value,{...filters,limit:pageSize.value,offset:(page.value-1)*pageSize.value});rows.value=result.items;total.value=result.total}catch(error){ElMessage.error(`加载平台用例失败：${(error as Error).message}`)}finally{loading.value=false}}
function applyFilters(){page.value=1;load()}
async function init(){try{if(spaceId.value)platforms.value=await listPlatforms(spaceId.value);await load()}catch(error){ElMessage.error(`初始化平台用例管理失败：${(error as Error).message}`)}}
function changeFilterPlatform(){filters.variant_id=undefined;applyFilters()}
async function openDetail(row:PlatformCaseSummary){if(!spaceId.value)return;drawer.value=true;detailLoading.value=true;try{detail.value=await getPlatformCase(row.id,spaceId.value)}catch(error){ElMessage.error((error as Error).message)}finally{detailLoading.value=false}}
function openEdit(){if(!detail.value)return;Object.assign(form,{platform_id:detail.value.platform_id,variant_id:detail.value.variant_id||undefined,filename:detail.value.filename,name:detail.value.name,kind:detail.value.kind,media_type:detail.value.media_type,content:detail.value.content});dialog.value=true}
function formatJson(){try{form.content=JSON.stringify(JSON.parse(form.content),null,2)}catch{ElMessage.warning('当前内容不是合法 JSON')}}
async function save(){if(!detail.value||!spaceId.value||!form.platform_id||!form.filename.trim()||!form.content)return; saving.value=true;try{const body={filename:form.filename,name:form.name,kind:form.kind,media_type:form.media_type,content:form.content};const saved=await updatePlatformCase(detail.value.id,spaceId.value,body);dialog.value=false;await load();await openDetail(saved);ElMessage.success('平台用例已保存')}catch(error){ElMessage.error((error as Error).message)}finally{saving.value=false}}
async function archive(){if(!detail.value||!spaceId.value)return;try{await ElMessageBox.confirm(`归档「${detail.value.filename}」？历史生成产物不会被删除。`,'确认归档',{type:'warning'});detail.value=await archivePlatformCase(detail.value.id,spaceId.value);await load();ElMessage.success('已归档')}catch(error){if(error!=='cancel')ElMessage.error((error as Error).message)}}
async function restore(){if(!detail.value||!spaceId.value)return;try{detail.value=await restorePlatformCase(detail.value.id,spaceId.value);await load();ElMessage.success('已恢复')}catch(error){ElMessage.error((error as Error).message)}}
onMounted(init)
</script>

<template><div class="page">
  <div class="page-header"><div><h1 class="page-title">平台用例管理</h1><p class="page-subtitle">编辑生成产物的管理副本；历史生成记录与原始产物始终保持不变。</p></div></div>
  <el-empty v-if="!spaceId" description="当前空间默认知识库配置异常，请到知识库管理检查"/>
  <template v-else><el-card shadow="never" class="filters"><el-form inline><el-form-item label="平台"><el-select v-model="filters.platform_id" clearable style="width:170px" @change="changeFilterPlatform"><el-option v-for="p in platforms" :key="p.id" :label="p.name" :value="p.id"/></el-select></el-form-item><el-form-item label="示例类型"><el-select v-model="filters.variant_id" clearable style="width:170px" @change="applyFilters"><el-option v-for="v in filterPlatform?.variants||[]" :key="v.id" :label="v.name" :value="v.id"/></el-select></el-form-item><el-form-item label="格式"><el-select v-model="filters.media_type" clearable style="width:160px" @change="applyFilters"><el-option label="JSON" value="application/json"/><el-option label="CSV" value="text/csv"/><el-option label="Markdown" value="text/markdown"/><el-option label="纯文本" value="text/plain"/></el-select></el-form-item><el-form-item><el-input v-model="filters.search" clearable placeholder="搜索文件名或名称" @keyup.enter="applyFilters" @clear="applyFilters"/></el-form-item><el-form-item><el-checkbox v-model="filters.include_archived" @change="applyFilters">显示已归档</el-checkbox></el-form-item><el-form-item><el-button @click="applyFilters">查询</el-button></el-form-item></el-form></el-card>
  <el-card shadow="never" class="list"><el-table v-loading="loading" :data="rows" row-key="id" @row-click="openDetail"><el-table-column prop="filename" label="文件名" min-width="180"/><el-table-column prop="platform_name" label="平台"/><el-table-column prop="variant_name" label="示例类型"/><el-table-column prop="media_type" label="格式" min-width="140"/><el-table-column prop="source_run_id" label="来源 Run" width="105"><template #default="{row}">{{row.source_run_id||'手工'}}</template></el-table-column><el-table-column prop="updated_at" label="更新时间" min-width="175"/><el-table-column prop="status" label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='active'?'success':'info'">{{row.status==='active'?'使用中':'已归档'}}</el-tag></template></el-table-column></el-table><el-empty v-if="!loading&&!rows.length" description="暂无平台用例，可通过生成平台产物获得"/><el-pagination v-if="total" v-model:current-page="page" v-model:page-size="pageSize" class="pager" :page-sizes="[20,50,100]" layout="total, sizes, prev, pager, next" :total="total" @current-change="load" @size-change="()=>{page=1;load()}"/></el-card></template>

  <el-drawer v-model="drawer" size="62%" title="平台用例详情"><div v-loading="detailLoading" v-if="detail" class="detail"><div class="detail-head"><div><h2>{{detail.name||detail.filename}}</h2><p>{{detail.filename}} · {{detail.media_type}} · {{detail.content_hash}}</p><p>平台：{{detail.platform_name}} · 示例类型：{{detail.variant_name||'未指定'}} · 来源：{{detail.source_run_id?`Run ${detail.source_run_id}`:'手工创建'}}</p></div><div><el-button @click="download">下载</el-button><el-button v-if="detail.status==='active'" @click="openEdit">编辑</el-button><el-button v-if="detail.status==='active'" type="danger" plain @click="archive">归档</el-button><el-button v-else type="success" plain @click="restore">恢复</el-button></div></div><el-alert v-if="detail.source_artifact_id" title="这是历史产物的管理副本，编辑或归档不会改变原始生成记录。" type="info" :closable="false"/>
    <div class="preview"><template v-if="detail.render_mode==='json'"><el-alert v-if="detail.json_truncated" title="JSON 结构较深或节点较多，树形预览已截断；下载或编辑仍使用完整原文。" type="warning" :closable="false"/><el-tree :data="jsonTree" node-key="id" :default-expanded-keys="['root']"/></template><div v-else-if="detail.render_mode==='csv'" class="csv"><el-alert v-if="detail.csv_truncated" :title="`预览已截断；共 ${detail.csv_total_rows} 行，最多显示 200 行 × 100 列`" type="warning" :closable="false"/><el-table :data="detail.csv_rows" border><el-table-column v-for="(header,index) in detail.csv_headers" :key="index" :label="header" min-width="140"><template #default="scope">{{scope.row[index]}}</template></el-table-column></el-table></div><MarkdownView v-else-if="detail.render_mode==='markdown'" :content="detail.content"/><pre v-else>{{detail.content}}</pre></div></div></el-drawer>

  <el-dialog v-model="dialog" title="编辑平台用例" width="760px"><el-form label-position="top"><div class="form-grid"><el-form-item label="平台"><el-select v-model="form.platform_id" disabled><el-option v-for="p in platforms" :key="p.id" :label="p.name" :value="p.id"/></el-select></el-form-item><el-form-item label="示例类型（可选）"><el-select v-model="form.variant_id" clearable disabled><el-option v-for="v in formPlatform?.variants||[]" :key="v.id" :label="v.name" :value="v.id"/></el-select></el-form-item><el-form-item label="文件名"><el-input v-model="form.filename"/></el-form-item><el-form-item label="显示名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="Kind"><el-select v-model="form.kind"><el-option v-for="k in ['case','data','relation','combined','attachment']" :key="k" :label="k" :value="k"/></el-select></el-form-item><el-form-item label="媒体类型"><el-input v-model="form.media_type"/></el-form-item></div><el-form-item label="原始内容"><template #label><span>原始内容 <el-button v-if="form.media_type.includes('json')||form.filename.toLowerCase().endsWith('.json')" link type="primary" @click="formatJson">格式化 JSON</el-button></span></template><el-input v-model="form.content" type="textarea" :rows="16"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
</div></template>

<style scoped>.filters{margin-bottom:16px}.filters :deep(.el-form-item){margin-bottom:0}.list :deep(.el-table__row){cursor:pointer}.pager{justify-content:flex-end;margin-top:16px}.detail-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.detail-head h2{margin:0 0 8px}.detail-head p{margin:4px 0;color:var(--cg-text-muted);word-break:break-all}.preview{margin-top:18px;border:1px solid var(--cg-border);border-radius:10px;padding:16px;min-height:240px;overflow:auto}.preview .el-alert{margin-bottom:12px}.preview pre{white-space:pre-wrap;word-break:break-word;margin:0}.csv{max-width:100%;overflow-x:auto}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}@media(max-width:900px){.form-grid{grid-template-columns:1fr}.detail-head{display:block}}</style>
